version: '3.8'

services:
  db:
    image: postgres:16
    container_name: task_db
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
      POSTGRES_DB: task
    ports:
      - "5437:5432"

  app:
    image: myapp:latest  # Исправлено: теперь используется имя образа, созданного через Dockerfile
    container_name: myapp
    depends_on:
      - db
    volumes:
      - ./config/config.yaml:/app/config/config.yaml  # Монтируем config.yaml в контейнер
      - ./internal/migrations:/app/migrations  # Монтируем папку с миграциями
    environment:
      CONFIG_PATH: /app/config/config.yaml  # Переменная окружения для указания пути к конфигу
    ports:
      - "8082:8082"  # Выделение порта для приложения
    command: ["./myapp"]  # Исправлено: теперь используется собранное приложение
    entrypoint: /bin/sh -c "migrate -path /app/migrations -database postgres://task:task@db:5432/task?sslmode=disable up && ./myapp"